### ISSUE TITLE
Remove generated dirs on sbt clean ?

### ISSUE THREAD

**Issue by Antwnis** [51zero/avro4s#7]
When compiling a project having avro4s as a dependency - classes are generated at folders:
 `avro4s-core` and `avro4s-generator` 

Can they be automatically removed on `sbt clean` ?

**Comment by sksamuel** [comment]
They should be getting cleaned, I'm not sure if the entire folder is being
removed. I can't really alter the way sbt clean works.

**Comment by Antwnis** [comment]
Can you not generate the classes under `target/avro4s-core` and `target/avro4s-generated` ?

**Comment by sksamuel** [comment]
Oh the generated classes. My bad. I'll make it an option.
